import LoadingState from './LoadingState'
import type { QuoteResult } from '../types/quote'

function money(value: number) { return `$${value.toFixed(2)}` }
function formatDate(value: string) { return new Date(value).toLocaleString([], { month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit' }) }
function provider(value: string) { return value === 'finnhub' ? 'Finnhub' : value }

export default function MarketOverview({ results, loading, error }: { results: QuoteResult[]; loading: boolean; error: string | null }) {
  return <section className="panel overview-panel" aria-label="Current market quotes"><div className="panel-header"><div><h2 className="panel-title">Market overview</h2><p className="panel-subtitle">Current quotes · refreshed every 45 seconds while visible</p></div><span className="live-key"><i /> quote layer</span></div>{loading && !results.length ? <LoadingState label="Loading current quotes" /> : <><div className="quote-grid">{results.map(({ symbol, quote, error: quoteError, freshness }) => <article className={`quote-card ${freshness === 'STALE' ? 'is-stale' : ''}`} key={symbol}><div className="quote-top"><strong>{symbol}</strong><span className={`freshness freshness-${(quote?.freshness ?? freshness).toLowerCase()}`}>{quote?.freshness ?? freshness}</span></div>{quote ? <><div className="quote-price">{money(quote.price)}</div><div className={`quote-change ${quote.change >= 0 ? 'positive' : 'negative'}`}>{quote.change >= 0 ? '+' : ''}{quote.change.toFixed(2)} ({quote.change_percent >= 0 ? '+' : ''}{quote.change_percent.toFixed(2)}%)</div><dl><div><dt>Market</dt><dd>{quote.market_status.replace('_', ' ')}</dd></div><div><dt>Provider</dt><dd>{provider(quote.provider)}</dd></div><div><dt>Provider time</dt><dd title={quote.provider_timestamp}>{formatDate(quote.provider_timestamp)}</dd></div><div><dt>Retrieved</dt><dd title={quote.retrieved_at}>{formatDate(quote.retrieved_at)}</dd></div></dl>{quoteError && <p className="quote-warning">{quoteError}</p>}</> : <div className="quote-unavailable"><strong>Quote unavailable</strong><span>{quoteError ?? 'No current quote returned.'}</span></div>}</article>)}</div>{error && <p className="quote-api-error">{error} Historical data remains available below.</p>}</>}</section>
}
