import { useState } from 'react'
import DataTable from '../components/DataTable'
import PriceChart from '../components/PriceChart'
import PriceSummary from '../components/PriceSummary'
import StockHeader from '../components/StockHeader'
import StockSelector from '../components/StockSelector'
import { useStock } from '../hooks/useStock'

function dateString(date: Date) { return date.toISOString().slice(0, 10) }
function formatProvider(value: string | undefined) { return value ? value.split('_').map((part) => part.charAt(0).toUpperCase() + part.slice(1)).join(' ') : '—' }
export default function Dashboard({ symbol, supportedSymbols, onSymbolChange }: { symbol: string; supportedSymbols: readonly string[]; onSymbolChange: (symbol: string) => void }) {
  const today = new Date(), [endDate, setEndDate] = useState(dateString(today)), [startDate, setStartDate] = useState(dateString(new Date(today.getFullYear() - 1, today.getMonth(), today.getDate())))
  const { stock, prices, loading, pricesLoading, error, pricesError } = useStock(symbol, startDate, endDate)
  return <div className="app-shell"><header className="topbar"><div className="brand"><span className="brand-mark">EI</span><span className="brand-name">Equity Intelligence</span></div><div className="topbar-note">PERSISTED MARKET DATA / RESEARCH VIEW</div></header><main className="page"><div className="page-heading"><div><div className="eyebrow">United States / Equities</div><h1>Market view</h1><p className="heading-copy">A focused read on persisted pricing history, built for careful research and clear comparisons.</p></div><div className="data-note">Source timestamps are supplied by the API.<br />This view is not real-time or investment advice.</div></div><StockSelector symbols={supportedSymbols} selected={symbol} onChange={onSymbolChange} /><div className="panel summary-grid"><StockHeader stock={stock} symbol={symbol} /><PriceSummary latest={stock?.latest_price} loading={loading} /></div>{error && !stock ? <div className="panel"><div className="state error"><strong>{symbol} is not available</strong><span>{error}</span></div></div> : <div className="content-grid"><section className="panel chart-panel"><div className="panel-header"><div><h2 className="panel-title">Closing price</h2><p className="panel-subtitle">Historical close / {prices.length} observations</p></div><div className="range-controls"><label htmlFor="start-date">From</label><input className="date-input" id="start-date" type="date" value={startDate} max={endDate} onChange={(event) => setStartDate(event.target.value)} /><label htmlFor="end-date">To</label><input className="date-input" id="end-date" type="date" value={endDate} min={startDate} onChange={(event) => setEndDate(event.target.value)} /></div></div><PriceChart prices={prices} loading={pricesLoading} error={pricesError} /><div className="provenance">Provider <span>{formatProvider(stock?.latest_price?.provider)}</span> · Latest persisted observation timestamp <span>{stock?.latest_price?.provider_timestamp ? new Date(stock.latest_price.provider_timestamp).toLocaleString() : '—'}</span></div></section><section className="panel table-panel"><div className="panel-header"><div><h2 className="panel-title">OHLCV history</h2><p className="panel-subtitle">Historical data · Open · high · low · close · volume</p></div></div><DataTable prices={prices} loading={pricesLoading} error={pricesError} /></section></div>}<p className="footer-note">Showing historical data persisted by the Equity Intelligence API for {symbol}. Symbols without persisted records remain unavailable.</p></main></div>
}
